//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades.ConexionBD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BarandillasEntities : DbContext
    {
        public BarandillasEntities()
            : base("name=BarandillasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<RelacionCamposTablas_BD> RelacionCamposTablas_BD { get; set; }
        public virtual DbSet<RelacionesTablas_BD> RelacionesTablas_BD { get; set; }
        public virtual DbSet<Tablas_BD> Tablas_BD { get; set; }
        public virtual DbSet<RelacionesDeTablas> RelacionesDeTablas { get; set; }
    }
}
