//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades.ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelacionesDeTablas
    {
        public int TablaID { get; set; }
        public string Nombre { get; set; }
        public int RelacionID { get; set; }
        public int TablaRelacionada { get; set; }
        public string Descripcion { get; set; }
    }
}
