//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades.ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tablas_BD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tablas_BD()
        {
            this.RelacionesTablas_BD = new HashSet<RelacionesTablas_BD>();
        }
    
        public int TablaID { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string TipoTabla { get; set; }
        public Nullable<bool> Estatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RelacionesTablas_BD> RelacionesTablas_BD { get; set; }
    }
}
